# Generated by Django 5.2.6 on 2026-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.avif', upload_to='profile_pics/'),
        ),
    ]
